/**
 * The Wi-Fi QR payload, as printed on router labels and generated by Android
 * and iOS under "Share Wi-Fi":
 *
 *   WIFI:T:WPA;S:HotelPalacio_Guest;P:s3cret;H:false;;
 *
 * One scan carries the network and the password together, which is the whole
 * point — no browser can read the SSID of the network the device is on, so
 * this is the only way both fields fill themselves.
 *
 * Fields arrive in any order, and `\` escapes any of \;,":  — a password with
 * a semicolon in it is the case that breaks a naive split.
 */

/** Splits on separators that aren't escaped, and unescapes as it goes. */
function fields(payload) {
  const out = []
  let key = null
  let buffer = ''

  for (let i = 0; i < payload.length; i++) {
    const char = payload[i]

    if (char === '\\') {
      // A trailing backslash escapes nothing; keep it rather than dropping a
      // character the writer may have meant literally.
      buffer += payload[++i] ?? '\\'
      continue
    }
    if (char === ':' && key === null) {
      key = buffer
      buffer = ''
      continue
    }
    if (char === ';') {
      if (key !== null) out.push([key.toUpperCase(), buffer])
      key = null
      buffer = ''
      continue
    }
    buffer += char
  }

  if (key !== null) out.push([key.toUpperCase(), buffer])
  return out
}

/**
 * A value wrapped in double quotes is hexadecimal per the spec — rare, and
 * decoding it into bytes we'd then have to guess an encoding for is worse than
 * handing back the digits. Quotes are stripped either way.
 */
const unquote = (value) =>
  value.startsWith('"') && value.endsWith('"') && value.length >= 2
    ? value.slice(1, -1)
    : value

/**
 * What a scanned code says, or null if it isn't a Wi-Fi code at all — a QR on
 * a router label is as likely to be a support URL or the serial number.
 */
export function parseWifiQr(text) {
  if (typeof text !== 'string') return null

  const trimmed = text.trim()
  if (!/^wifi:/i.test(trimmed)) return null

  const found = Object.fromEntries(fields(trimmed.slice('WIFI:'.length)))
  const ssid = unquote(found.S ?? '')
  if (!ssid) return null

  return {
    ssid,
    // An open network has no P field; empty password is a real answer, not a
    // missing one.
    password: unquote(found.P ?? ''),
    // nopass, WEP, WPA, WPA2-EAP — kept because "is this open" changes what
    // the guest is told, even though nothing branches on it yet.
    security: (found.T || 'nopass').toUpperCase(),
    hidden: /^true$/i.test(found.H ?? ''),
  }
}
